trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: leriksen/pipelines-azp-docker-linux

steps:
  - task: AzureCLI@2
    displayName: build image on ACR
    inputs:
      azureSubscription: sc_azdo
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |-
        cd docker
        az acr list -g azdo
        az acr build --registry "azdocr" --image "$(imageName)" --file "./Dockerfile" "."
