trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: leriksen/pipelines-azp-docker-linux

steps:
  - task: Docker@2
    displayName: login to docker
    inputs:
      command: login
      containerRegistry: docker.io
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: buildAndPush
      Dockerfile: ./docker/Dockerfile
      tags: |
        $(Build.BuildId)
        latest
