trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: leriksen/pipelines-azp-docker-linux

steps:
  - task: AzureCLI@2
    displayName: build image on ACR
    inputs:
      azureSubscription: sc_azdo
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |-
        az acr build --registry "azdocr.azurecr.io" --image "$(imageName)" --file "./docker/Dockerfile" "."

#  - task: Docker@2
#    displayName: login to docker
#    inputs:
#      command: login
#      containerRegistry: docker.io
#  - task: Docker@2
#    displayName: Build an image
#    inputs:
#      repository: $(imageName)
#      command: buildAndPush
#      Dockerfile: ./docker/Dockerfile
#      tags: |
#        $(Build.BuildId)
#        latest
